import { writeFileSync } from 'fs'
import { FormatterCallback } from '../formatter'

const htmlFormatter: FormatterCallback = function (formatter) {
  formatter.on('end', (event) => {
    let fileContent = '<!DOCTYPE html><html lang="en">'
    fileContent += '\n<head>'
    fileContent += '\n<meta charset="UTF-8">'
    fileContent +=
      '\n<meta name="viewport" content="width=device-width, initial-scale=1">'
    fileContent += '\n<title>HTML Hint Violation Report</title>'
    fileContent += '\n<meta name="generator" content="HTMLHint">'
    fileContent += '\n</head>'
    fileContent += '\n<body style="font-family: Arial, helvetica, sans-serif;">'
    fileContent += '\n<h1>Violation Report</h1>'
    fileContent += '\n<main>'
    fileContent += '\n<table style="border:1px solid #ccc;margin-bottom:20px;">'
    fileContent +=
      '\n<tr><th>Number#</th><th>File Name</th><th>Line Number</th><th>Message</th></tr>'

    for (const { file, messages } of event.arrAllMessages) {
      fileContent += messages
        .map(
          ({ line, message }, i) =>
            `\n<tr><td>${
              i + 1
            }</td><td>${file}</td><td>${line}</td><td>${message}</td></tr>`
        )
        .join('')
    }

    fileContent += '</table>'
    fileContent +=
      '\n<footer><small style="opacity:0.5">Generated by <a href="https://htmlhint.com" target="_blank" rel="noopener">HTMLHint</a></small></footer>'
    fileContent += '\n</main>'
    fileContent += '\n</body>'
    fileContent += '</html>'
    console.log(fileContent)
    writeFileSync('report.html', fileContent)
  })
}

module.exports = htmlFormatter
